server:
  port: 9191
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/db
    username: dbuser
    password: dbpass
    driverClassName: org.h2.Driver
  application:
    name: payment-service
